server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YimengL/config-repo
          default-label: master
          timeout: 5
          clone-on-start: true # Clones the remote repository locally on startup
          force-pull: true # Forces pulling the remote repository and discarding any local changes

logging:
  level:
    org.springframework.cloud.config: DEBUG