apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  type: ClusterIP
  selector:
    app: config-service
  ports:
  - protocol: TCP
    port: 80 # The port exposed by the service
    targetPort: 8888 # The port exposed by the Pods targeted by the service