name: Commit Stage
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: yimengl/config-service
  VERSION: latest

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

  package:
    name: Package and Publish
